version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: portal_admin
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "3307:3306"

  php-apache:
    build: .
    image: php:8.1-apache
    volumes:
      - ./www:/var/www/html
      - ./vendor:/var/www/vendor
      - ./src:/var/www/src
    depends_on:
      - db
    ports:
      - "8081:80"

volumes:
  db_data:
